// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksImages = {
  /**
   * Image
   */
  items: Array<{
    /**
     * Image
     */
    imageId: string;

    /**
     * Description of the image for visually impaired users (alt text)
     */
    altText: string;

    /**
     * Caption
     */
    caption?: string;
  }>;

  /**
   * Size
   */
  size?: "full" | "medium" | "small";

  /**
   * Alignment
   */
  alignment?: "left" | "right";

  /**
   * Shape
   */
  form?:
    | {
        /**
         * Selected
         */
        _selected: "rounded";

        /**
         * Rounded
         */
        rounded: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "notch";

        /**
         * Notch (cutout)
         */
        notch: {
          /**
           * Corner
           */
          corner?: "bottom-right" | "bottom-left" | "top-right" | "top-left";

          /**
           * Cutout width in percent
           */
          width?: number;

          /**
           * Cutout depth in percent
           */
          depth?: number;
        };
      };
};
