// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksImages = {
  /**
   * Image
   */
  items: Array<{
    /**
     * Image
     */
    imageId: string;

    /**
     * Description of the image for visually impaired users (alt text)
     */
    altText: string;

    /**
     * Caption
     */
    caption?: string;
  }>;

  /**
   * Form
   */
  form?: "rounded" | "notch";

  /**
   * Utsnittets kant
   */
  notchEdge?: "bottom" | "top" | "left" | "right";

  /**
   * Utsnittets plassering (0–100)
   */
  notchOffset?: number;

  /**
   * Utsnittets bredde i prosent
   */
  notchWidth?: number;

  /**
   * Utsnittets dybde i prosent
   */
  notchDepth?: number;
};
