// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ContentHeader = {
  /**
   * Kicker
   */
  kicker?: string;

  /**
   * Title
   */
  title?: string;

  /**
   * Intro
   */
  intro?: string;
};
