// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Blocks = import("./blocks").Blocks;
export type BlocksAccordion = import("./blocks-accordion").BlocksAccordion;
export type BlocksCard = import("./blocks-card").BlocksCard;
export type BlocksCards = import("./blocks-cards").BlocksCards;
export type BlocksCode = import("./blocks-code").BlocksCode;
export type BlocksConfig = import("./blocks-config").BlocksConfig;
export type BlocksFactbox = import("./blocks-factbox").BlocksFactbox;
export type BlocksImagePlacement = import("./blocks-image-placement").BlocksImagePlacement;
export type BlocksImages = import("./blocks-images").BlocksImages;
export type BlocksLink = import("./blocks-link").BlocksLink;
export type BlocksQuote = import("./blocks-quote").BlocksQuote;
export type BlocksReuse = import("./blocks-reuse").BlocksReuse;
export type BlocksText = import("./blocks-text").BlocksText;
export type BlocksTheme = import("./blocks-theme").BlocksTheme;
export type ContentHeader = import("./content-header").ContentHeader;
