// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksTextImage = {
  /**
   * Kicker
   */
  kicker?: string;

  /**
   * Title
   */
  title: string;

  /**
   * Text
   */
  text?: string;

  /**
   * Button text
   */
  buttonText?: string;

  /**
   * Link
   */
  link:
    | {
        /**
         * Selected
         */
        _selected: "internal";

        /**
         * Internal
         */
        internal: {
          /**
           * Internal link
           */
          internalLink: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "external";

        /**
         * External
         */
        external: {
          /**
           * External link
           */
          externalLink: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "none";

        /**
         * None
         */
        none: Record<string, unknown>;
      };

  /**
   * Image
   */
  imageId: string;

  /**
   * Alternative text for the image
   */
  altText: string;

  /**
   * Image placement
   */
  imagePlacement?: "right" | "left";

  /**
   * Shape
   */
  form?:
    | {
        /**
         * Selected
         */
        _selected: "rounded";

        /**
         * Rounded
         */
        rounded: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "notch";

        /**
         * Notch (cutout)
         */
        notch: {
          /**
           * Corner
           */
          corner?: "bottom-right" | "bottom-left" | "top-right" | "top-left";

          /**
           * Cutout width in percent
           */
          width?: number;

          /**
           * Cutout depth in percent
           */
          depth?: number;
        };
      };

  /**
   * Theme
   */
  theme?: string;
};
