// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SiteContent = {
  /**
   * Title
   */
  title?: string;

  /**
   * Intro
   */
  intro?: string;

  /**
   * Content blocks
   */
  blocks?: Array<
    | {
        /**
         * Selected
         */
        _selected: "blocks-text";

        /**
         * Text
         */
        "blocks-text": {
          /**
           * Title
           */
          title?: string;

          /**
           * Text
           */
          text?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-accordion";

        /**
         * Accordion
         */
        "blocks-accordion": {
          /**
           * Title
           */
          title?: string;

          /**
           * Accordion element
           */
          items: Array<{
            /**
             * Title
             */
            title: string;

            /**
             * Text
             */
            text: string;
          }>;

          /**
           * Theme
           */
          theme?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-quote";

        /**
         * Quote
         */
        "blocks-quote": {
          /**
           * Text
           */
          text: string;

          /**
           * Name of person quoted
           */
          author?: string;

          /**
           * Author Image
           */
          imageId?: string;

          /**
           * Title
           */
          publicationTitle?: string;

          /**
           * Url
           */
          publicationUrl?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-factbox";

        /**
         * Factbox
         */
        "blocks-factbox": {
          /**
           * Title
           */
          title?: string;

          /**
           * Text
           */
          text: string;

          /**
           * Theme
           */
          theme?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-images";

        /**
         * Images
         */
        "blocks-images": {
          /**
           * Image
           */
          items: Array<{
            /**
             * Image
             */
            imageId: string;

            /**
             * Description of the image for visually impaired users (alt text)
             */
            altText: string;

            /**
             * Caption
             */
            caption?: string;
          }>;
        };
      }
  >;
};
