// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksCode = {
  /**
   * Code
   */
  code: string;

  /**
   * Language
   */
  language?: "tsx" | "ts" | "js" | "css" | "html" | "bash" | "json" | "graphql" | "xml";

  /**
   * Label
   */
  label?: string;
};
