// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Page = import("./page").Page;

declare global {
  namespace XP {
    interface ContentTypes {
      "no.rodekors.docs:page": Page;
    }
  }
}
