// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SiteContent = import("./site-content").SiteContent;

declare global {
  interface XpXData {
    "no-rodekors-docs"?: {
      "site-content"?: SiteContent;
    };
  }
}
