// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksView = {
  /**
   * Block title
   */
  title?: string;

  /**
   * Content blocks
   */
  blocks?: Array<
    | {
        /**
         * Selected
         */
        _selected: "blocks-text";

        /**
         * Text
         */
        "blocks-text": {
          /**
           * Title
           */
          title?: string;

          /**
           * Text
           */
          text?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-accordion";

        /**
         * Accordion
         */
        "blocks-accordion": {
          /**
           * Title
           */
          title?: string;

          /**
           * Accordion element
           */
          items: Array<{
            /**
             * Title
             */
            title: string;

            /**
             * Text
             */
            text: string;
          }>;

          /**
           * Theme
           */
          theme?: string;
        };
      }
  >;
};
