// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type PageComponents = {
  /**
   * Title
   */
  title?: string;

  /**
   * Intro
   */
  intro?: string;

  /**
   * Show search field
   */
  showSearch: boolean;
};
