# Settings for publishing to a Maven repo
group = no.rodekors

# Gradle Project settings
projectName = designsystem-docs
version = 0.0.0-SNAPSHOT

# XP App values
appDisplayName = Røde Kors Designsystem Docs
appName = no.rodekors.docs
vendorName = Røde kors
vendorUrl = https://www.rodekors.no/

# Min required version of XP
xpVersion = 7.16.2
