// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksHero = {
  /**
   * Badge
   */
  badge?: string;

  /**
   * Badge meta
   */
  badgeMeta?: string;

  /**
   * Kicker
   */
  kicker?: string;

  /**
   * Title
   */
  title: string;

  /**
   * Lead
   */
  lead?: string;

  /**
   * Photo
   */
  image?: string;

  /**
   * Call to action
   */
  actions?: Array<{
    /**
     * Button text
     */
    linkText: string;

    /**
     * Link
     */
    link:
      | {
          /**
           * Selected
           */
          _selected: "internal";

          /**
           * Internal
           */
          internal: {
            /**
             * Internal link
             */
            internalLink: string;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "external";

          /**
           * External
           */
          external: {
            /**
             * External link
             */
            externalLink: string;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "none";

          /**
           * None
           */
          none: Record<string, unknown>;
        };
  }>;
};
