schema: schema.graphql
extensions:
  endpoints:
    dev:
      url: http://localhost:8080/site/designsystem-docs/master
      subscription:
        url: ws://localhost:8080/site/designsystem-docs/master
      introspect: true
