"""Access control entry."""
type AccessControlEntry {
  principal: PrincipalKey
  allow: [Permission]
  deny: [Permission]
}

"""Aggregation input type"""
input AggregationInput {
  subAggregations: [AggregationInput]
  name: String!
  terms: TermsAggregationInput
  stats: StatsAggregationInput
  range: RangeAggregationInput
  dateRange: DateRangeAggregationInput
  dateHistogram: DateHistogramAggregationInput
  geoDistance: GeoDistanceAggregationInput
  min: MinAggregationInput
  max: MaxAggregationInput
  count: ValueCountAggregationInput
}

"""Attachment."""
type Attachment {
  name: String
  label: String
  size: Int
  mimeType: String
  attachmentUrl(download: Boolean, type: UrlType, params: JSON): String
}

"""BooleanDSLExpressionInput type"""
input BooleanDSLExpressionInput {
  should: [QueryDSLInput]
  must: [QueryDSLInput]
  mustNot: [QueryDSLInput]
  filter: [QueryDSLInput]
  boost: Float
}

"""BooleanFilter input type"""
input BooleanFilterInput {
  must: [FilterInput]
  mustNot: [FilterInput]
  should: [FilterInput]
}

"""Component."""
type Component {
  type: ComponentType!
  path: String!
  part: PartComponentData
  page: PageComponentData
  layout: LayoutComponentData
  image: ImageComponentData
  text: TextComponentData
  fragment: FragmentComponentData
}

"""Component type."""
enum ComponentType {
  page
  layout
  image
  part
  text
  fragment
}

"""Content."""
interface Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
}

"""ContentConnection."""
type ContentConnection {
  totalCount: Int!
  edges: [ContentEdge]
  pageInfo: PageInfo
}

"""ContentEdge."""
type ContentEdge {
  node: Content!
  cursor: String!
}

"""Content path type."""
enum ContentPathType {
  siteRelative
}

"""Content type."""
type ContentType {
  name: String
  displayName: String
  description: String
  superType: String
  abstract: Boolean
  final: Boolean
  allowChildContent: Boolean
  contentDisplayNameScript: String
  icon: Icon
  form: [FormItem]
  formAsJson: JSON
}

"""DSLExpressionValueInput type"""
input DSLExpressionValueInput {
  string: String
  double: Float
  long: Int
  boolean: Boolean
  localDate: Date
  localDateTime: LocalDateTime
  localTime: LocalTime
  instant: DateTime
}

"""An RFC-3339 compliant Full Date Scalar"""
scalar Date

"""DateHistogram aggregation input type"""
input DateHistogramAggregationInput {
  field: String!
  interval: String
  format: String
  minDocCount: Int
}

"""DateRange aggregation input type"""
input DateRangeAggregationInput {
  field: String!
  format: String
  ranges: [DateRangeInput]
}

"""Date range input type"""
input DateRangeInput {
  key: String
  from: String
  to: String
}

"""A slightly refined version of RFC-3339 compliant DateTime Scalar"""
scalar DateTime

"""Default value."""
type DefaultValue {
  value: String
  type: String
}

"""DSL Geo Point Distance type."""
enum DslGeoPointDistanceType {
  m
  meters
  in
  inch
  yd
  yards
  ft
  feet
  km
  kilometers
  NM
  nmi
  nauticalmiles
  mm
  millimeters
  cm
  centimeters
  mi
  miles
}

"""DSL Operator type."""
enum DslOperatorType {
  OR
  AND
}

"""DSL sort direction type."""
enum DslSortDirectionType {
  ASC
  DESC
}

"""ExistsDSLExpressionInput type"""
input ExistsDSLExpressionInput {
  field: String!
  boost: Float
}

"""ExistsFilter input type"""
input ExistsFilterInput {
  field: String!
}

"""Extra data."""
type ExtraData {
  no_rodekors_docs: XData_no_rodekors_docs_ApplicationConfig
  media: XData_media_ApplicationConfig
  base: XData_base_ApplicationConfig
}

"""Filter input type"""
input FilterInput {
  boolean: BooleanFilterInput
  exists: ExistsFilterInput
  notExists: NotExistsFilterInput
  hasValue: HasValueFilterInput
  ids: IdsFilterInput
}

"""Form input."""
type FormInput implements FormItem {
  formItemType: FormItemType
  name: String
  label: String
  customText: String
  helpText: String
  validationRegexp: String
  maximize: Boolean
  inputType: String
  occurrences: Occurrences
  defaultValue: DefaultValue
  configAsJson: JSON
}

"""FormItem."""
interface FormItem {
  formItemType: FormItemType
  name: String
  label: String
}

"""Form item set."""
type FormItemSet implements FormItem {
  formItemType: FormItemType
  name: String
  label: String
  customText: String
  helpText: String
  occurrences: Occurrences
  items: [FormItem]
}

"""Form item type"""
enum FormItemType {
  ItemSet
  Layout
  Input
  OptionSet
}

"""Form layout."""
type FormLayout implements FormItem {
  formItemType: FormItemType
  name: String
  label: String
  items: [FormItem]
}

"""Form option set."""
type FormOptionSet implements FormItem {
  formItemType: FormItemType
  name: String
  label: String
  expanded: Boolean
  helpText: String
  occurrences: Occurrences
  selection: Occurrences
  options: [FormOptionSetOption]
}

"""Form option set option."""
type FormOptionSetOption {
  name: String
  label: String
  helpText: String
  default: Boolean
  items: [FormItem]
}

"""Fragment component data."""
type FragmentComponentData {
  id: ID!
  fragment: Content
}

"""FulltextDSLExpressionInput type"""
input FulltextDSLExpressionInput {
  fields: [String]!
  query: String!
  operator: DslOperatorType
}

"""GeoDistance aggregation input type"""
input GeoDistanceAggregationInput {
  field: String!
  unit: String
  origin: GeoPointInput!
  ranges: [NumberRangeInput]!
}

"""GeoPoint."""
type GeoPoint {
  value: String
  latitude: Float
  longitude: Float
}

"""Geo range input type"""
input GeoPointInput {
  lat: String!
  lon: String!
}

"""GeoPoint Sort Dsl input type"""
input GeoPointSortDslInput {
  lat: Float!
  lon: Float!
}

"""HasValueFilter input type"""
input HasValueFilterInput {
  field: String!
  stringValues: [String]
  intValues: [Int]
  floatValues: [Float]
  booleanValues: [Boolean]
}

"""Headless CMS"""
type HeadlessCms {
  queryDsl(query: QueryDSLInput, offset: Int, first: Int, sort: [SortDslInput]): [Content]
  getChildren(key: ID, offset: Int, first: Int, sort: String): [Content]
  queryConnection(query: String!, after: String, first: Int, sort: String, contentTypes: [String], aggregations: [AggregationInput], filters: [FilterInput]): QueryContentConnection
  getType(name: String!): ContentType
  blocks(key: ID!): [no_rodekors_docs_Block]
  get(key: ID): Content
  getPermissions(key: ID): Permissions
  query(query: String, offset: Int, first: Int, sort: String, contentTypes: [String], filters: [FilterInput]): [Content]
  getSite: portal_Site
  getChildrenConnection(key: ID, after: String, first: Int, sort: String): ContentConnection
  queryDslConnection(query: QueryDSLInput!, after: String, first: Int, aggregations: [AggregationInput], highlight: HighlightInputType, sort: [SortDslInput]): QueryDSLContentConnection
  getTypes: [ContentType]
}

"""
Indicates if the snippet should be HTML encoded: default (no encoding) or html.
"""
enum HighlightEncoderType {
  default
  html
}

"""
Specifies how text should be broken up in highlight snippets: simple or span (default).
"""
enum HighlightFragmenterType {
  simple
  span
}

"""HighlightInputType input type"""
input HighlightInputType {
  properties: [HighlightPropertiesInputType]!
  encoder: HighlightEncoderType
  tagsSchema: HighlightTagsSchemaType
  fragmenter: HighlightFragmenterType
  fragmentSize: Int
  noMatchSize: Int
  numberOfFragments: Int
  order: HighlightOrderType
  preTag: String
  postTag: String
  requireFieldMatch: Boolean
}

"""
Sorts highlighted fragments by score when set to score. Defaults to none - will be displayed in the same order in which fragments appear in the property.
"""
enum HighlightOrderType {
  score
  none
}

"""HighlightProperties input type"""
input HighlightPropertiesInputType {
  propertyName: String!
  fragmenter: HighlightFragmenterType
  fragmentSize: Int
  noMatchSize: Int
  numberOfFragments: Int
  order: HighlightOrderType
  preTag: String
  postTag: String
  requireFieldMatch: Boolean
}

"""Set to styled to use the built-in tag schema."""
enum HighlightTagsSchemaType {
  styled
}

"""Icon."""
type Icon {
  mimeType: String
  modifiedTime: String
}

"""IdsFilter input type"""
input IdsFilterInput {
  values: [String]
}

"""Image type."""
type Image {
  image: Content
  ref: String
  style: ImageStyle
}

"""Image component data."""
type ImageComponentData {
  id: ID!
  caption: String
  image: media_Image
}

"""ImageStyle type."""
type ImageStyle {
  name: String
  aspectRatio: String
  filter: String
}

"""InDSLExpressionInput type"""
input InDSLExpressionInput {
  field: String!
  boost: Float
  stringValues: [String]
  doubleValues: [Float]
  longValues: [Int]
  booleanValues: [Boolean]
  localDateValues: [Date]
  localDateTimeValues: [LocalDateTime]
  localTimeValues: [LocalTime]
  instantValues: [DateTime]
}

"""A JSON scalar"""
scalar JSON

"""Layout component data."""
type LayoutComponentData {
  descriptor: String!
  configAsJson: JSON
}

"""LikeDSLExpressionInput type"""
input LikeDSLExpressionInput {
  field: String!
  boost: Float
  value: String!
}

"""Link type."""
type Link {
  ref: String
  uri: String
  media: Media
  content: Content
}

"""LocalDateTime scalar"""
scalar LocalDateTime

"""LocalTime scalar"""
scalar LocalTime

"""Macro type."""
type Macro {
  ref: String
  name: String
  descriptor: String
  config: MacroConfig
}

"""Macro config type."""
type MacroConfig {
  disable: Macro_system_disable_DataConfig
  embed: Macro_system_embed_DataConfig
}

"""
Macro descriptor data config for application ['system'] and descriptor ['disable']
"""
type Macro_system_disable_DataConfig {
  body: String
}

"""
Macro descriptor data config for application ['system'] and descriptor ['embed']
"""
type Macro_system_embed_DataConfig {
  body: String
}

"""MatchAllDSLExpressionInput type"""
input MatchAllDSLExpressionInput {
  boost: Float
}

"""MaxAggregation input type"""
input MaxAggregationInput {
  field: String!
}

"""Media type."""
type Media {
  content: Content
  intent: MediaIntentType
}

"""Media focal point."""
type MediaFocalPoint {
  x: Float
  y: Float
}

"""Media intent type."""
enum MediaIntentType {
  download
  inline
}

"""Media uploader."""
type MediaUploader {
  attachment: String
  focalPoint: MediaFocalPoint
}

"""MinAggregation input type"""
input MinAggregationInput {
  field: String!
}

"""NgramDSLExpressionInput type"""
input NgramDSLExpressionInput {
  fields: [String]!
  query: String!
  operator: DslOperatorType
}

"""NotExistsFilter input type"""
input NotExistsFilterInput {
  field: String!
}

"""Number range input type"""
input NumberRangeInput {
  key: String
  from: Float
  to: Float
}

"""Occurrences."""
type Occurrences {
  maximum: Int
  minimum: Int
}

"""Page component data."""
type PageComponentData {
  descriptor: String
  customized: Boolean
  template: Content
  configAsJson: JSON
}

"""PageInfo"""
type PageInfo {
  startCursor: String!
  endCursor: String!
  hasNext: Boolean!
}

"""Part component data."""
type PartComponentData {
  descriptor: String!
  configAsJson: JSON
  config: PartComponentDataConfig
}

"""Part component config."""
type PartComponentDataConfig {
  no_rodekors_docs: Part_no_rodekors_docs_ComponentDataApplicationConfig
}

"""Part component application config for application ['no.rodekors.docs']"""
type Part_no_rodekors_docs_ComponentDataApplicationConfig {
  blocks_view: Part_no_rodekors_docs_blocks_view
}

"""
Part component application config for application ['no.rodekors.docs'] and descriptor ['blocks-view']
"""
type Part_no_rodekors_docs_blocks_view {
  title: String
  blocks(offset: Int, first: Int): [Part_no_rodekors_docs_blocks_view_Blocks]
}

"""Content blocks"""
type Part_no_rodekors_docs_blocks_view_Blocks {
  _selected: Part_no_rodekors_docs_blocks_view_Blocks_OptionEnum
  blocks_text: Part_no_rodekors_docs_blocks_view_BlocksText
  blocks_accordion: Part_no_rodekors_docs_blocks_view_BlocksAccordion
  blocks_quote: Part_no_rodekors_docs_blocks_view_BlocksQuote
  blocks_factbox: Part_no_rodekors_docs_blocks_view_BlocksFactbox
  blocks_images: Part_no_rodekors_docs_blocks_view_BlocksImages
  blocks_cards: Part_no_rodekors_docs_blocks_view_BlocksCards
}

"""Accordion"""
type Part_no_rodekors_docs_blocks_view_BlocksAccordion {
  title: String
  items(offset: Int, first: Int): [Part_no_rodekors_docs_blocks_view_Items]
  theme: String
}

"""Cards"""
type Part_no_rodekors_docs_blocks_view_BlocksCards {
  title: String
  imageClass: String
  columnsClass: String
  items(offset: Int, first: Int): [Part_no_rodekors_docs_blocks_view_Items_3]
}

"""Factbox"""
type Part_no_rodekors_docs_blocks_view_BlocksFactbox {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
  theme: String
}

"""Images"""
type Part_no_rodekors_docs_blocks_view_BlocksImages {
  items(offset: Int, first: Int): [Part_no_rodekors_docs_blocks_view_Items_2]
}

"""Quote"""
type Part_no_rodekors_docs_blocks_view_BlocksQuote {
  text(processHtml: ProcessHtmlInput): RichText
  author: String
  imageId: Content
  publicationTitle: String
  publicationUrl: String
}

"""Text"""
type Part_no_rodekors_docs_blocks_view_BlocksText {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
}

"""Content blocks option enum."""
enum Part_no_rodekors_docs_blocks_view_Blocks_OptionEnum {
  blocks_text
  blocks_accordion
  blocks_quote
  blocks_factbox
  blocks_images
  blocks_cards
}

"""External"""
type Part_no_rodekors_docs_blocks_view_External {
  externalLink: String
}

"""Internal"""
type Part_no_rodekors_docs_blocks_view_Internal {
  internalLink: Content
}

"""Accordion element"""
type Part_no_rodekors_docs_blocks_view_Items {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
}

"""Image"""
type Part_no_rodekors_docs_blocks_view_Items_2 {
  imageId: Content
  altText: String
  caption: String
}

"""Cards"""
type Part_no_rodekors_docs_blocks_view_Items_3 {
  title: String
  link: Part_no_rodekors_docs_blocks_view_Link
  kicker: String
  text: String
  imageId: Content
  theme: String
}

"""Link"""
type Part_no_rodekors_docs_blocks_view_Link {
  _selected: Part_no_rodekors_docs_blocks_view_Link_OptionEnum
  internal: Part_no_rodekors_docs_blocks_view_Internal
  external: Part_no_rodekors_docs_blocks_view_External
  none: String
}

"""Link option enum."""
enum Part_no_rodekors_docs_blocks_view_Link_OptionEnum {
  internal
  external
  none
}

"""PathMatchDSLExpressionInput type"""
input PathMatchDSLExpressionInput {
  field: String!
  path: String!
  minimumMatch: Int
  boost: Float
}

"""Permission."""
enum Permission {
  READ
  CREATE
  MODIFY
  DELETE
  PUBLISH
  READ_PERMISSIONS
  WRITE_PERMISSIONS
}

"""Permissions."""
type Permissions {
  inheritsPermissions: Boolean
  permissions: [AccessControlEntry]
}

"""Principal key."""
type PrincipalKey {
  value: String
  type: PrincipalType
  idProvider: String
  principalId: String
}

"""Principal type."""
enum PrincipalType {
  user
  group
  role
}

"""Process HTML input type"""
input ProcessHtmlInput {
  type: UrlType
  imageWidths: [Int]
  imageSizes: String
}

"""Publish information."""
type PublishInfo {
  from: String
  to: String
  first: String
}

"""Query"""
type Query {
  guillotine(siteKey: String): HeadlessCms
}

"""QueryContentConnection."""
type QueryContentConnection {
  totalCount: Int!
  edges: [ContentEdge]
  pageInfo: PageInfo
  aggregationsAsJson: JSON
}

"""QueryDSLContentConnection."""
type QueryDSLContentConnection {
  totalCount: Int!
  edges: [ContentEdge]
  pageInfo: PageInfo
  aggregationsAsJson: JSON
  highlightAsJson: JSON
}

"""QueryDSLInput type"""
input QueryDSLInput {
  boolean: BooleanDSLExpressionInput
  ngram: NgramDSLExpressionInput
  stemmed: StemmedDSLExpressionInput
  fulltext: FulltextDSLExpressionInput
  matchAll: MatchAllDSLExpressionInput
  pathMatch: PathMatchDSLExpressionInput
  range: RangeDSLExpressionInput
  term: TermDSLExpressionInput
  like: LikeDSLExpressionInput
  in: InDSLExpressionInput
  exists: ExistsDSLExpressionInput
}

"""Range aggregation input type"""
input RangeAggregationInput {
  field: String!
  ranges: [NumberRangeInput]
}

"""RangeDSLExpressionInput type"""
input RangeDSLExpressionInput {
  field: String!
  lt: DSLExpressionValueInput
  lte: DSLExpressionValueInput
  gt: DSLExpressionValueInput
  gte: DSLExpressionValueInput
  boost: Float
}

"""RichText type."""
type RichText {
  raw: String
  processedHtml: String
  macrosAsJson: JSON
  macros: [Macro]
  images: [Image]
  links: [Link]
}

"""Site configurator."""
type SiteConfigurator {
  applicationKey: String
  configAsJson: JSON
}

"""Sort Dsl input type"""
input SortDslInput {
  field: String!
  direction: DslSortDirectionType
  location: GeoPointSortDslInput
  unit: DslGeoPointDistanceType
}

"""Stats aggregation input type"""
input StatsAggregationInput {
  field: String!
}

"""StemmedDSLExpressionInput type"""
input StemmedDSLExpressionInput {
  fields: [String]!
  query: String!
  language: String!
  operator: DslOperatorType
  boost: Float
}

"""TermDSLExpressionInput type"""
input TermDSLExpressionInput {
  field: String!
  boost: Float
  value: DSLExpressionValueInput!
}

"""Terms aggregation input type"""
input TermsAggregationInput {
  field: String!
  order: String
  size: Int
  minDocCount: Int
}

"""Text component data."""
type TextComponentData {
  value(processHtml: ProcessHtmlInput): RichText!
}

"""UntypedContent"""
type UntypedContent implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
}

"""URL type."""
enum UrlType {
  server
  absolute
}

"""ValueCount Aggregation input type"""
input ValueCountAggregationInput {
  field: String!
}

"""XDataApplicationConfig for application ['base']"""
type XData_base_ApplicationConfig {
  gpsInfo: XData_base_gpsInfo_DataConfig
}

"""Extra data config for application ['base}'] and descriptor ['gpsInfo']"""
type XData_base_gpsInfo_DataConfig {
  geoPoint: GeoPoint
  altitude: String
  direction: String
}

"""XDataApplicationConfig for application ['media']"""
type XData_media_ApplicationConfig {
  imageInfo: XData_media_imageInfo_DataConfig
  cameraInfo: XData_media_cameraInfo_DataConfig
}

"""
Extra data config for application ['media}'] and descriptor ['cameraInfo']
"""
type XData_media_cameraInfo_DataConfig {
  date: LocalDateTime
  make: String
  model: String
  lens: String
  iso: String
  focalLength: String
  focalLength35: String
  exposureBias: String
  aperture(offset: Int, first: Int): [String]
  shutterTime: String
  flash: String
  autoFlashCompensation: String
  whiteBalance: String
  exposureProgram: String
  shootingMode: String
  meteringMode: String
  exposureMode: String
  focusDistance: String
  orientation: String
}

"""
Extra data config for application ['media}'] and descriptor ['imageInfo']
"""
type XData_media_imageInfo_DataConfig {
  pixelSize: String
  imageHeight: String
  imageWidth: String
  contentType: String
  description: String
  byteSize: String
  colorSpace(offset: Int, first: Int): [String]
  fileSource: String
}

"""XDataApplicationConfig for application ['no.rodekors.docs']"""
type XData_no_rodekors_docs_ApplicationConfig {
  site_content: XData_no_rodekors_docs_site_content_DataConfig
}

"""
Extra data config for application ['no.rodekors.docs}'] and descriptor ['site-content']
"""
type XData_no_rodekors_docs_site_content_DataConfig {
  title: String
  intro(processHtml: ProcessHtmlInput): RichText
  blocks(offset: Int, first: Int): [XData_no_rodekors_docs_site_content_DataConfig_Blocks]
}

"""Content blocks"""
type XData_no_rodekors_docs_site_content_DataConfig_Blocks {
  _selected: XData_no_rodekors_docs_site_content_DataConfig_Blocks_OptionEnum
  blocks_text: XData_no_rodekors_docs_site_content_DataConfig_BlocksText
  blocks_accordion: XData_no_rodekors_docs_site_content_DataConfig_BlocksAccordion
  blocks_quote: XData_no_rodekors_docs_site_content_DataConfig_BlocksQuote
  blocks_factbox: XData_no_rodekors_docs_site_content_DataConfig_BlocksFactbox
  blocks_images: XData_no_rodekors_docs_site_content_DataConfig_BlocksImages
  blocks_cards: XData_no_rodekors_docs_site_content_DataConfig_BlocksCards
}

"""Accordion"""
type XData_no_rodekors_docs_site_content_DataConfig_BlocksAccordion {
  title: String
  items(offset: Int, first: Int): [XData_no_rodekors_docs_site_content_DataConfig_Items]
  theme: String
}

"""Cards"""
type XData_no_rodekors_docs_site_content_DataConfig_BlocksCards {
  title: String
  imageClass: String
  columnsClass: String
  items(offset: Int, first: Int): [XData_no_rodekors_docs_site_content_DataConfig_Items_3]
}

"""Factbox"""
type XData_no_rodekors_docs_site_content_DataConfig_BlocksFactbox {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
  theme: String
}

"""Images"""
type XData_no_rodekors_docs_site_content_DataConfig_BlocksImages {
  items(offset: Int, first: Int): [XData_no_rodekors_docs_site_content_DataConfig_Items_2]
}

"""Quote"""
type XData_no_rodekors_docs_site_content_DataConfig_BlocksQuote {
  text(processHtml: ProcessHtmlInput): RichText
  author: String
  imageId: Content
  publicationTitle: String
  publicationUrl: String
}

"""Text"""
type XData_no_rodekors_docs_site_content_DataConfig_BlocksText {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
}

"""Content blocks option enum."""
enum XData_no_rodekors_docs_site_content_DataConfig_Blocks_OptionEnum {
  blocks_text
  blocks_accordion
  blocks_quote
  blocks_factbox
  blocks_images
  blocks_cards
}

"""External"""
type XData_no_rodekors_docs_site_content_DataConfig_External {
  externalLink: String
}

"""Internal"""
type XData_no_rodekors_docs_site_content_DataConfig_Internal {
  internalLink: Content
}

"""Accordion element"""
type XData_no_rodekors_docs_site_content_DataConfig_Items {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
}

"""Image"""
type XData_no_rodekors_docs_site_content_DataConfig_Items_2 {
  imageId: Content
  altText: String
  caption: String
}

"""Cards"""
type XData_no_rodekors_docs_site_content_DataConfig_Items_3 {
  title: String
  link: XData_no_rodekors_docs_site_content_DataConfig_Link
  kicker: String
  text: String
  imageId: Content
  theme: String
}

"""Link"""
type XData_no_rodekors_docs_site_content_DataConfig_Link {
  _selected: XData_no_rodekors_docs_site_content_DataConfig_Link_OptionEnum
  internal: XData_no_rodekors_docs_site_content_DataConfig_Internal
  external: XData_no_rodekors_docs_site_content_DataConfig_External
  none: String
}

"""Link option enum."""
enum XData_no_rodekors_docs_site_content_DataConfig_Link_OptionEnum {
  internal
  external
  none
}

"""Folder - base:folder"""
type base_Folder implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
}

"""Media - base:media"""
type base_Media implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
}

"""Shortcut - base:shortcut"""
type base_Shortcut implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  data: base_Shortcut_Data
}

"""Shortcut - base:shortcut data"""
type base_Shortcut_Data {
  target: Content
  parameters(offset: Int, first: Int): [base_Shortcut_Parameters]
}

"""Parameters"""
type base_Shortcut_Parameters {
  name: String
  value: String
}

"""Structured - base:structured"""
type base_Structured implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
}

"""Unstructured - base:unstructured"""
type base_Unstructured implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
}

"""Archive - media:archive"""
type media_Archive implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Archive_Data
}

"""Archive - media:archive data"""
type media_Archive_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Audio - media:audio"""
type media_Audio implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Audio_Data
}

"""Audio - media:audio data"""
type media_Audio_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Code - media:code"""
type media_Code implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Code_Data
}

"""Code - media:code data"""
type media_Code_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Data - media:data"""
type media_Data implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Data_Data
}

"""Data - media:data data"""
type media_Data_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Document - media:document"""
type media_Document implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Document_Data
}

"""Document - media:document data"""
type media_Document_Data {
  media: Content
  abstract: String
  tags(offset: Int, first: Int): [String]
}

"""Executable - media:executable"""
type media_Executable implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Executable_Data
}

"""Executable - media:executable data"""
type media_Executable_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Image - media:image"""
type media_Image implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  imageUrl(scale: String!, quality: Int, type: UrlType, background: String, format: String, filter: String, params: JSON): String
  data: media_Image_Data
}

"""Image - media:image data"""
type media_Image_Data {
  media: MediaUploader
  caption: String
  altText: String
  artist(offset: Int, first: Int): [String]
  copyright: String
  tags(offset: Int, first: Int): [String]
}

"""Presentation - media:presentation"""
type media_Presentation implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Presentation_Data
}

"""Presentation - media:presentation data"""
type media_Presentation_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Spreadsheet - media:spreadsheet"""
type media_Spreadsheet implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Spreadsheet_Data
}

"""Spreadsheet - media:spreadsheet data"""
type media_Spreadsheet_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Text - media:text"""
type media_Text implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Text_Data
}

"""Text - media:text data"""
type media_Text_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Unknown - media:unknown"""
type media_Unknown implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Unknown_Data
}

"""Unknown - media:unknown data"""
type media_Unknown_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Vector - media:vector"""
type media_Vector implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Vector_Data
}

"""Vector - media:vector data"""
type media_Vector_Data {
  media: Content
  caption: String
  artist(offset: Int, first: Int): [String]
  copyright: String
  tags(offset: Int, first: Int): [String]
}

"""Video - media:video"""
type media_Video implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  mediaUrl(download: Boolean, type: UrlType, params: JSON): String
  data: media_Video_Data
}

"""Video - media:video data"""
type media_Video_Data {
  media: Content
  tags(offset: Int, first: Int): [String]
}

"""Your page content is build by a sequence of blocks."""
union no_rodekors_docs_Block = no_rodekors_docs_BlockText | no_rodekors_docs_BlockAccordion | no_rodekors_docs_BlockQuote | no_rodekors_docs_BlockFactbox | no_rodekors_docs_BlockImages | no_rodekors_docs_BlockCards

"""A list of expandable sections"""
type no_rodekors_docs_BlockAccordion {
  title: String
  items: [no_rodekors_docs_BlockText]
  theme: String
}

"""One card in a cards block"""
type no_rodekors_docs_BlockCard {
  title: String
  kicker: String
  text: String
  imageUrl(scale: String!): String
  theme: String
  url: String
  contentPath: String
}

"""Cards can have a title, text, image and can link to content"""
type no_rodekors_docs_BlockCards {
  title: String
  columns: Int
  imagePlacement: String
  items: [no_rodekors_docs_BlockCard]
}

"""A box containing text that can have different background colors"""
type no_rodekors_docs_BlockFactbox {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
  theme: String
}

"""One image in an images block"""
type no_rodekors_docs_BlockImage {
  imageUrl(scale: String!): String
  altText: String
  caption: String
}

"""An image gallery or an image that can be expanded"""
type no_rodekors_docs_BlockImages {
  items: [no_rodekors_docs_BlockImage]
}

"""A stylized quote with the image of the author"""
type no_rodekors_docs_BlockQuote {
  text(processHtml: ProcessHtmlInput): RichText
  author: String
  imageUrl(scale: String!): String
  publicationTitle: String
  publicationUrl: String
}

"""Rich text field that can contain lists and tables"""
type no_rodekors_docs_BlockText {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
}

"""Page - no.rodekors.docs:page"""
type no_rodekors_docs_Page implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  data: no_rodekors_docs_Page_Data
}

"""Content blocks"""
type no_rodekors_docs_Page_Blocks {
  _selected: no_rodekors_docs_Page_Blocks_OptionEnum
  blocks_text: no_rodekors_docs_Page_BlocksText
  blocks_accordion: no_rodekors_docs_Page_BlocksAccordion
  blocks_quote: no_rodekors_docs_Page_BlocksQuote
  blocks_factbox: no_rodekors_docs_Page_BlocksFactbox
  blocks_images: no_rodekors_docs_Page_BlocksImages
  blocks_cards: no_rodekors_docs_Page_BlocksCards
}

"""Accordion"""
type no_rodekors_docs_Page_BlocksAccordion {
  title: String
  items(offset: Int, first: Int): [no_rodekors_docs_Page_Items]
  theme: String
}

"""Cards"""
type no_rodekors_docs_Page_BlocksCards {
  title: String
  imageClass: String
  columnsClass: String
  items(offset: Int, first: Int): [no_rodekors_docs_Page_Items_3]
}

"""Factbox"""
type no_rodekors_docs_Page_BlocksFactbox {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
  theme: String
}

"""Images"""
type no_rodekors_docs_Page_BlocksImages {
  items(offset: Int, first: Int): [no_rodekors_docs_Page_Items_2]
}

"""Quote"""
type no_rodekors_docs_Page_BlocksQuote {
  text(processHtml: ProcessHtmlInput): RichText
  author: String
  imageId: Content
  publicationTitle: String
  publicationUrl: String
}

"""Text"""
type no_rodekors_docs_Page_BlocksText {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
}

"""Content blocks option enum."""
enum no_rodekors_docs_Page_Blocks_OptionEnum {
  blocks_text
  blocks_accordion
  blocks_quote
  blocks_factbox
  blocks_images
  blocks_cards
}

"""Page - no.rodekors.docs:page data"""
type no_rodekors_docs_Page_Data {
  title: String
  intro(processHtml: ProcessHtmlInput): RichText
  blocks(offset: Int, first: Int): [no_rodekors_docs_Page_Blocks]
}

"""External"""
type no_rodekors_docs_Page_External {
  externalLink: String
}

"""Internal"""
type no_rodekors_docs_Page_Internal {
  internalLink: Content
}

"""Accordion element"""
type no_rodekors_docs_Page_Items {
  title: String
  text(processHtml: ProcessHtmlInput): RichText
}

"""Image"""
type no_rodekors_docs_Page_Items_2 {
  imageId: Content
  altText: String
  caption: String
}

"""Cards"""
type no_rodekors_docs_Page_Items_3 {
  title: String
  link: no_rodekors_docs_Page_Link
  kicker: String
  text: String
  imageId: Content
  theme: String
}

"""Link"""
type no_rodekors_docs_Page_Link {
  _selected: no_rodekors_docs_Page_Link_OptionEnum
  internal: no_rodekors_docs_Page_Internal
  external: no_rodekors_docs_Page_External
  none: String
}

"""Link option enum."""
enum no_rodekors_docs_Page_Link_OptionEnum {
  internal
  external
  none
}

"""Fragment - portal:fragment"""
type portal_Fragment implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
}

"""Page-template - portal:page-template"""
type portal_PageTemplate implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  data: portal_PageTemplate_Data
}

"""Page-template - portal:page-template data"""
type portal_PageTemplate_Data {
  supports(offset: Int, first: Int): [String]
}

"""Site - portal:site"""
type portal_Site implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
  data: portal_Site_Data
}

"""Site - portal:site data"""
type portal_Site_Data {
  description: String
}

"""Template-folder - portal:template-folder"""
type portal_TemplateFolder implements Content {
  _id: ID!
  _name: String!
  _path(type: ContentPathType): String!
  _references: [Content]
  _score: Float
  creator: PrincipalKey
  modifier: PrincipalKey
  createdTime: DateTime
  modifiedTime: DateTime
  owner: PrincipalKey
  type: String
  contentType: ContentType
  displayName: String
  hasChildren: Boolean
  language: String
  valid: Boolean
  dataAsJson: JSON
  x: ExtraData
  xAsJson: JSON
  pageAsJson(resolveTemplate: Boolean, resolveFragment: Boolean): JSON
  pageTemplate: Content
  components(resolveTemplate: Boolean, resolveFragment: Boolean): [Component]
  attachments: [Attachment]
  publish: PublishInfo
  pageUrl(type: UrlType, params: JSON): String
  site: portal_Site
  parent: Content
  children(offset: Int, first: Int, sort: String): [Content]
  childrenConnection(after: String, first: Int, sort: String): ContentConnection
  permissions: Permissions
}
