// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksDemo = {
  /**
   * Demo
   */
  demo: "button-variants" | "alert-severities" | "card-scopes" | "details-basic" | "tag-badge";

  /**
   * Title
   */
  title?: string;
};
