// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksView = import("./blocks-view").BlocksView;
export type ContentHeader = import("./content-header").ContentHeader;

declare global {
  interface XpPartMap {
    "no.rodekors.www:blocks-view": BlocksView;
    "no.rodekors.www:content-header": ContentHeader;
  }
}
