// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type PageChangelog = {
  /**
   * Title
   */
  title?: string;

  /**
   * Intro
   */
  intro?: string;

  /**
   * Number of releases
   */
  maxReleases?: number;
};
